const wordList = [
  { word: "Act", id: "Act" },
  { word: "Apple", id: "Apple" },
  { word: "Bed", id: "Bed" },
  { word: "Body", id: "Body" },
  { word: "Clap", id: "Clap" },
  { word: "Chicken", id: "Chicken" },
  { word: "Dart", id: "Dart" },
  { word: "Dino", id: "Dino" },
  { word: "Ear", id: "Ear" },
  { word: "Easy", id: "Easy" },
  { word: "For", id: "For" },
  { word: "Fire", id: "Fire" },
  { word: "Get", id: "Get" },
  { word: "Going", id: "Going" },
  { word: "Here", id: "Here" },
  { word: "Happy", id: "Happy" },
  { word: "If", id: "If" },
  { word: "Into", id: "Into" },
  { word: "Job", id: "Job" },
  { word: "July", id: "July" },
  { word: "Kid", id: "Kid" },
  { word: "Kilo", id: "Kilo" },
  { word: "Late", id: "Late" },
  { word: "Later", id: "Later" },
  { word: "Make", id: "Make" },
  { word: "Menu", id: "Menu" },
  { word: "Name", id: "Name" },
  { word: "Ninety", id: "Ninety" },
  { word: "Odd", id: "Odd" },
  { word: "Oval", id: "Oval" },
  { word: "Pea", id: "Pea" },
  { word: "Pizza", id: "Pizza" },
  { word: "Quick", id: "Quick" },
  { word: "Quicker", id: "Quicker" },
  { word: "Read", id: "Read" },
  { word: "River", id: "River" },
  { word: "Soak", id: "Soak" },
  { word: "Sorry", id: "Sorry" },
  { word: "Tall", id: "Tall" },
  { word: "Thirty", id: "Thirty" },
  { word: "Up", id: "Up" },
  { word: "Unit", id: "Unit" },
  { word: "Vase", id: "Vase" },
  { word: "Very", id: "Very" },
  { word: "Wait", id: "Wait" },
  { word: "Water", id: "Water" },
  { word: "Mix", id: "Mix" },
  { word: "Xmas", id: "Xmas" },
  { word: "Yes", id: "Yes" },
  { word: "Yesterday", id: "Yesterday" },
  { word: "Zen", id: "Zen" },
  { word: "Zebra", id: "Zebra" },
  { word: "Background", id: "Background Noise" },
];

export default wordList;
